#!/bin/bash
echo "🤖 Configuración de Bot de Telegram"
echo "=================================="
echo ""
echo "Pasos:"
echo "1. Abre Telegram y busca @BotFather"
echo "2. Envía /newbot y sigue las instrucciones"
echo "3. Copia el token que te dé"
echo "4. Busca tu chat ID con @userinfobot"
echo ""
echo "📝 En n8n, ve a:"
echo "   Settings → Credentials → Add Credential"
echo "   Selecciona 'Telegram Bot API'"
echo "   Pon el token y el chat ID"
echo ""
echo "🔗 Luego conecta el nodo 'Telegram Notify' en el workflow"
