# modules/team_translator.py - VERSI?N AMPLIADA
"""
Traductor inteligente de nombres de equipos para The Odds API
Incluye ligas de Am?rica Latina, Europa y el mundo
"""

class TeamTranslator:
    """
    Convierte nombres de equipos de capturas de pantalla
    a los nombres que usa The Odds API
    """
    
    def __init__(self):
        # Diccionario de traducciones expandido
        self.translations = {
            # ========== ALEMANIA (Existente) ==========
            "1. fc saarbr?cken": "1. FC Saarbr?cken",
            "fc saarbr?cken": "1. FC Saarbr?cken",
            "saarbr?cken": "1. FC Saarbr?cken",
            "saarbruecken": "1. FC Saarbr?cken",
            "alemannia aachen": "Alemannia Aachen",
            "aachen": "Alemannia Aachen",
            "bayer leverkusen": "Bayer Leverkusen",
            "leverkusen": "Bayer Leverkusen",
            "fc ingolstadt 04": "FC Ingolstadt 04",
            "ingolstadt": "FC Ingolstadt 04",
            "hamburger sv": "Hamburger SV",
            "hamburgo": "Hamburger SV",
            "hamburg": "Hamburger SV",
            "hansa rostock": "Hansa Rostock",
            "rostock": "Hansa Rostock",
            "msv duisburg": "MSV Duisburg",
            "duisburg": "MSV Duisburg",
            "rot-weiss essen": "Rot-Weiss Essen",
            "essen": "Rot-Weiss Essen",
            "schweinfurt": "Schweinfurt",
            "tsv havelse": "TSV Havelse",
            "havelse": "TSV Havelse",
            "waldhof mannheim": "Waldhof Mannheim",
            "mannheim": "Waldhof Mannheim",
            "wehen wiesbaden": "Wehen Wiesbaden",
            "wiesbaden": "Wehen Wiesbaden",
            
            # ========== GRECIA (Existente) ==========
            "ae kifisia fc": "AE Kifisia FC",
            "kifisia": "AE Kifisia FC",
            "paok thessaloniki": "PAOK Thessaloniki",
            "paok": "PAOK Thessaloniki",
            "paok sal?nica": "PAOK Thessaloniki",
            
            # ========== ITALIA (Existente) ==========
            "bari": "Bari",
            "carrarese": "Carrarese",
            "empoli": "Empoli",
            "frosinone": "Frosinone",
            "juve stabia": "Juve Stabia",
            "mantova": "Mantova",
            "palermo": "Palermo",
            "pescara": "Pescara",
            "sampdoria": "Sampdoria",
            "us catanzaro 1929": "US Catanzaro 1929",
            "catanzaro": "US Catanzaro 1929",
            
            # ========== ESPA?A (Ampliado) ==========
            "real madrid": "Real Madrid",
            "madrid": "Real Madrid",
            "barcelona": "Barcelona",
            "bar?a": "Barcelona",
            "atletico madrid": "Atl?tico Madrid",
            "atl?tico madrid": "Atl?tico Madrid",
            "atletico": "Atl?tico Madrid",
            "atl?tico": "Atl?tico Madrid",
            "real sociedad": "Real Sociedad",
            "real soc": "Real Sociedad",
            "athletic bilbao": "Athletic Bilbao",
            "athletic club": "Athletic Bilbao",
            "bilbao": "Athletic Bilbao",
            "valencia": "Valencia",
            "sevilla": "Sevilla",
            "betis": "Real Betis",
            "real betis": "Real Betis",
            "villareal": "Villarreal",
            "villarreal": "Villarreal",
            "celta": "Celta Vigo",
            "celta vigo": "Celta Vigo",
            "rayo vallecano": "Rayo Vallecano",
            "rayo": "Rayo Vallecano",
            "espanyol": "Espanyol",
            "getafe": "Getafe",
            "osasuna": "Osasuna",
            "granada": "Granada",
            "mallorca": "Mallorca",
            "alaves": "Alav?s",
            "alav?s": "Alav?s",
            "cadiz": "C?diz",
            "c?diz": "C?diz",
            "elche": "Elche",
            "levante": "Levante",
            "girona": "Girona",
            "oviedo": "Real Oviedo",
            "real oviedo": "Real Oviedo",
            "sporting gijon": "Sporting Gij?n",
            "sporting": "Sporting Gij?n",
            "zaragoza": "Real Zaragoza",
            "real zaragoza": "Real Zaragoza",
            "tenerife": "Tenerife",
            "las palmas": "Las Palmas",
            "eibar": "Eibar",
            "leganes": "Legan?s",
            "legan?s": "Legan?s",
            "mirandes": "Mirand?s",
            "mirand?s": "Mirand?s",
            "burgos": "Burgos",
            "cartagena": "Cartagena",
            "racing santander": "Racing Santander",
            "racing": "Racing Santander",
            "ferrol": "Racing Ferrol",
            "racing ferrol": "Racing Ferrol",
            "alcorcon": "Alcorc?n",
            "alcorc?n": "Alcorc?n",
            "ibiza": "Ibiza",
            "andorra": "FC Andorra",
            "fc andorra": "FC Andorra",
            
            # ========== INGLATERRA (Ampliado) ==========
            "manchester city": "Manchester City",
            "man city": "Manchester City",
            "manchester united": "Manchester United",
            "man utd": "Manchester United",
            "liverpool": "Liverpool",
            "chelsea": "Chelsea",
            "arsenal": "Arsenal",
            "tottenham": "Tottenham Hotspur",
            "spurs": "Tottenham Hotspur",
            "newcastle": "Newcastle United",
            "newcastle united": "Newcastle United",
            "leicester": "Leicester City",
            "leicester city": "Leicester City",
            "west ham": "West Ham United",
            "west ham united": "West Ham United",
            "aston villa": "Aston Villa",
            "villa": "Aston Villa",
            "everton": "Everton",
            "leeds": "Leeds United",
            "leeds united": "Leeds United",
            "wolves": "Wolverhampton Wanderers",
            "wolverhampton": "Wolverhampton Wanderers",
            "southampton": "Southampton",
            "crystal palace": "Crystal Palace",
            "brighton": "Brighton and Hove Albion",
            "brighton and hove albion": "Brighton and Hove Albion",
            "fulham": "Fulham",
            "brentford": "Brentford",
            "nottingham": "Nottingham Forest",
            "nottingham forest": "Nottingham Forest",
            "bournemouth": "AFC Bournemouth",
            "afc bournemouth": "AFC Bournemouth",
            
            # ========== M?XICO - LIGA MX ==========
            "america": "Club Am?rica",
            "club america": "Club Am?rica",
            "chivas": "Guadalajara",
            "guadalajara": "Guadalajara",
            "cruz azul": "Cruz Azul",
            "pumas": "UNAM",
            "unam": "UNAM",
            "tigres": "Tigres UANL",
            "tigres uanl": "Tigres UANL",
            "monterrey": "Monterrey",
            "rayados": "Monterrey",
            "toluca": "Toluca",
            "pachuca": "Pachuca",
            "santos": "Santos Laguna",
            "santos laguna": "Santos Laguna",
            "leon": "Le?n",
            "le?n": "Le?n",
            "puebla": "Puebla",
            "necaxa": "Necaxa",
            "atlas": "Atlas",
            "juarez": "Ju?rez",
            "fc juarez": "Ju?rez",
            "queretaro": "Quer?taro",
            "san luis": "Atl?tico San Luis",
            "atletico san luis": "Atl?tico San Luis",
            "atl?tico san luis": "Atl?tico San Luis",
            "mazatlan": "Mazatl?n",
            "mazatl?n": "Mazatl?n",
            "tijuana": "Tijuana",
            "xolos": "Tijuana",
            
            # ========== M?XICO - LIGA DE EXPANSI?N ==========
            "atletico morelia": "Atl?tico Morelia",
            "atl?tico morelia": "Atl?tico Morelia",
            "morelia": "Atl?tico Morelia",
            "zacatecas": "Mineros de Zacatecas",
            "mineros": "Mineros de Zacatecas",
            "celaya": "Celaya",
            "cancun": "Canc?n",
            "canc?n": "Canc?n",
            "cimarrones": "Cimarrones de Sonora",
            "sonora": "Cimarrones de Sonora",
            "correcaminos": "Correcaminos UAT",
            "uat": "Correcaminos UAT",
            "dorados": "Dorados de Sinaloa",
            "sinaloa": "Dorados de Sinaloa",
            "leones negros": "Leones Negros UdeG",
            "udeG": "Leones Negros UdeG",
            "tapatio": "Tapat?o",
            "tapat?o": "Tapat?o",
            "tepatitlan": "Tepatitl?n",
            "tepatitl?n": "Tepatitl?n",
            "tlaxcala": "Tlaxcala",
            "venados": "Venados FC",
            "yucatan": "Venados FC",
            "alebrijes": "Alebrijes de Oaxaca",
            "oaxaca": "Alebrijes de Oaxaca",
            
            # ========== EE.UU. - MLS ==========
            "inter miami": "Inter Miami",
            "miami": "Inter Miami",
            "la galaxy": "LA Galaxy",
            "galaxy": "LA Galaxy",
            "lafc": "Los Angeles FC",
            "los angeles fc": "Los Angeles FC",
            "new york red bulls": "New York Red Bulls",
            "ny red bulls": "New York Red Bulls",
            "new york city fc": "New York City FC",
            "nycfc": "New York City FC",
            "atlanta united": "Atlanta United",
            "atlanta": "Atlanta United",
            "seattle sounders": "Seattle Sounders",
            "sounders": "Seattle Sounders",
            "portland timbers": "Portland Timbers",
            "timbers": "Portland Timbers",
            "vancouver whitecaps": "Vancouver Whitecaps",
            "whitecaps": "Vancouver Whitecaps",
            "toronto fc": "Toronto FC",
            "toronto": "Toronto FC",
            "cf montreal": "CF Montr?al",
            "montreal": "CF Montr?al",
            "montr?al": "CF Montr?al",
            "chicago fire": "Chicago Fire",
            "fire": "Chicago Fire",
            "columbus crew": "Columbus Crew",
            "crew": "Columbus Crew",
            "dc united": "D.C. United",
            "dc united": "D.C. United",
            "fc dallas": "FC Dallas",
            "dallas": "FC Dallas",
            "houston dynamo": "Houston Dynamo",
            "dynamo": "Houston Dynamo",
            "sporting kc": "Sporting Kansas City",
            "sporting kansas city": "Sporting Kansas City",
            "kansas city": "Sporting Kansas City",
            "minnesota united": "Minnesota United",
            "minnesota": "Minnesota United",
            "nashville sc": "Nashville SC",
            "nashville": "Nashville SC",
            "new england": "New England Revolution",
            "revolution": "New England Revolution",
            "orlando city": "Orlando City",
            "orlando": "Orlando City",
            "philadelphia union": "Philadelphia Union",
            "philadelphia": "Philadelphia Union",
            "real salt lake": "Real Salt Lake",
            "salt lake": "Real Salt Lake",
            "san jose earthquakes": "San Jose Earthquakes",
            "earthquakes": "San Jose Earthquakes",
            "st louis city": "St. Louis City",
            "st. louis city": "St. Louis City",
            "st louis": "St. Louis City",
            "cincinnati": "FC Cincinnati",
            "fc cincinnati": "FC Cincinnati",
            "charlotte fc": "Charlotte FC",
            "charlotte": "Charlotte FC",
            "austin fc": "Austin FC",
            "austin": "Austin FC",
            "colorado rapids": "Colorado Rapids",
            "rapids": "Colorado Rapids",
            
            # ========== BRASIL - SERIE A ==========
            "flamengo": "Flamengo",
            "fluminense": "Fluminense",
            "vasco": "Vasco da Gama",
            "vasco da gama": "Vasco da Gama",
            "botafogo": "Botafogo",
            "corinthians": "Corinthians",
            "sao paulo": "S?o Paulo",
            "s?o paulo": "S?o Paulo",
            "palmeiras": "Palmeiras",
            "santos": "Santos",
            "gremio": "Gr?mio",
            "gr?mio": "Gr?mio",
            "internacional": "Internacional",
            "inter rs": "Internacional",
            "atletico mineiro": "Atl?tico Mineiro",
            "atl?tico mineiro": "Atl?tico Mineiro",
            "atletico paranaense": "Athletico Paranaense",
            "athletico paranaense": "Athletico Paranaense",
            "athletico": "Athletico Paranaense",
            "cruzeiro": "Cruzeiro",
            "bahia": "Bahia",
            "bah?a": "Bahia",
            "ceara": "Cear?",
            "cear?": "Cear?",
            "fortaleza": "Fortaleza",
            "goias": "Goi?s",
            "goi?s": "Goi?s",
            "coritiba": "Coritiba",
            "avai": "Ava?",
            "ava?": "Ava?",
            "cuiaba": "Cuiab?",
            "cuiab?": "Cuiab?",
            "juventude": "Juventude",
            "red bull bragantino": "Red Bull Bragantino",
            "bragantino": "Red Bull Bragantino",
            "america mineiro": "Am?rica Mineiro",
            "am?rica mineiro": "Am?rica Mineiro",
            
            # ========== BRASIL - ESTADUAL ==========
            # Carioca
            "volta redonda": "Volta Redonda",
            "portuguesa": "Portuguesa RJ",
            "portuguesa rj": "Portuguesa RJ",
            "madureira": "Madureira",
            "boavista": "Boavista RJ",
            "boavista rj": "Boavista RJ",
            "nova iguacu": "Nova Igua?u",
            "nova igua?u": "Nova Igua?u",
            
            # Paulista
            "ituano": "Ituano",
            "mirassol": "Mirassol",
            "novorizontino": "Novorizontino",
            "ferroviaria": "Ferrovi?ria",
            "ferrovi?ria": "Ferrovi?ria",
            "guarani": "Guarani",
            "ponte preta": "Ponte Preta",
            "botafogo sp": "Botafogo SP",
            "botafogo sp": "Botafogo SP",
            "santo andr?": "Santo Andr?",
            
            # Gaucho
            "juventude": "Juventude",
            "caxias": "Caxias",
            "caxias rs": "Caxias",
            "sao jose rs": "S?o Jos? RS",
            "s?o jos? rs": "S?o Jos? RS",
            "ypiranga rs": "Ypiranga RS",
            
            # Mineiro
            "democrata gv": "Democrata GV",
            "caldense": "Caldense",
            "tombense": "Tombense",
            "patrocinense": "Patrocinense",
            
            # Paranaense
            "londrina": "Londrina",
            "operario pr": "Oper?rio PR",
            "oper?rio pr": "Oper?rio PR",
            "cascavel": "Cascavel",
            "maringa": "Maring?",
            "maring?": "Maring?",
            
            # Catarinense
            "chapecoense": "Chapecoense",
            "chapeco": "Chapecoense",
            "avai": "Ava?",
            "brusque": "Brusque",
            "figueirense": "Figueirense",
            "criciuma": "Crici?ma",
            "crici?ma": "Crici?ma",
            "joinville": "Joinville",
            
            # ========== ARGENTINA ==========
            "boca juniors": "Boca Juniors",
            "boca": "Boca Juniors",
            "river plate": "River Plate",
            "river": "River Plate",
            "racing": "Racing Club",
            "racing club": "Racing Club",
            "independiente": "Independiente",
            "san lorenzo": "San Lorenzo",
            "lanus": "Lan?s",
            "lan?s": "Lan?s",
            "velez": "V?lez Sarsfield",
            "velez sarsfield": "V?lez Sarsfield",
            "v?lez sarsfield": "V?lez Sarsfield",
            "tigre": "Tigre",
            "platense": "Platense",
            "newells": "Newell's Old Boys",
            "newell's old boys": "Newell's Old Boys",
            "newells old boys": "Newell's Old Boys",
            "rosario central": "Rosario Central",
            "rosario": "Rosario Central",
            "central": "Rosario Central",
            "argentinos juniors": "Argentinos Juniors",
            "argentinos": "Argentinos Juniors",
            "banfield": "Banfield",
            "gimnasia": "Gimnasia La Plata",
            "gimnasia la plata": "Gimnasia La Plata",
            "estudiantes": "Estudiantes La Plata",
            "estudiantes la plata": "Estudiantes La Plata",
            "huracan": "Hurac?n",
            "hurac?n": "Hurac?n",
            "talleres": "Talleres C?rdoba",
            "talleres cordoba": "Talleres C?rdoba",
            "talleres c?rdoba": "Talleres C?rdoba",
            "colon": "Col?n",
            "col?n": "Col?n",
            "union": "Uni?n Santa Fe",
            "union santa fe": "Uni?n Santa Fe",
            "uni?n santa fe": "Uni?n Santa Fe",
            "atletico tucuman": "Atl?tico Tucum?n",
            "atl?tico tucum?n": "Atl?tico Tucum?n",
            "tucuman": "Atl?tico Tucum?n",
            "tucum?n": "Atl?tico Tucum?n",
            "sarmiento": "Sarmiento Jun?n",
            "sarmiento junin": "Sarmiento Jun?n",
            "sarmiento jun?n": "Sarmiento Jun?n",
            "defensa y justicia": "Defensa y Justicia",
            "defensa": "Defensa y Justicia",
            "godoy cruz": "Godoy Cruz",
            "barracas central": "Barracas Central",
            "central cordoba": "Central C?rdoba",
            "central cordoba sde": "Central C?rdoba SdE",
            "arsenal sarandi": "Arsenal Sarand?",
            "arsenal": "Arsenal Sarand?",
            "aldosivi": "Aldosivi",
            
            # ========== CHILE ==========
            "colocolo": "Colo Colo",
            "colo colo": "Colo Colo",
            "universidad de chile": "Universidad de Chile",
            "universidad catolica": "Universidad Cat?lica",
            "catolica": "Universidad Cat?lica",
            "cat?lica": "Universidad Cat?lica",
            "union espanola": "Uni?n Espa?ola",
            "uni?n espa?ola": "Uni?n Espa?ola",
            "palestino": "Palestino",
            "ohiggins": "O'Higgins",
            "o'higgins": "O'Higgins",
            "everton vina": "Everton Vi?a",
            "everton vi?a": "Everton Vi?a",
            "cobresal": "Cobresal",
            "coquimbo unido": "Coquimbo Unido",
            "la serena": "La Serena",
            "audax italiano": "Audax Italiano",
            "huachipato": "Huachipato",
            "nublense": "?ublense",
            "?ublense": "?ublense",
            "curico unido": "Curic? Unido",
            "curic? unido": "Curic? Unido",
            "magallanes": "Magallanes",
            
            # ========== COLOMBIA ==========
            "atletico nacional": "Atl?tico Nacional",
            "atl?tico nacional": "Atl?tico Nacional",
            "nacional": "Atl?tico Nacional",
            "millonarios": "Millonarios",
            "millonarios fc": "Millonarios",
            "santa fe": "Independiente Santa Fe",
            "independiente santa fe": "Independiente Santa Fe",
            "america de cali": "Am?rica de Cali",
            "america cali": "Am?rica de Cali",
            "deportivo cali": "Deportivo Cali",
            "cali": "Deportivo Cali",
            "junior": "Junior FC",
            "junior barranquilla": "Junior FC",
            "once caldas": "Once Caldas",
            "la equidad": "La Equidad",
            "equidad": "La Equidad",
            "deportes tolima": "Deportes Tolima",
            "tolima": "Deportes Tolima",
            "deportivo pasto": "Deportivo Pasto",
            "pasto": "Deportivo Pasto",
            "atletico huila": "Atl?tico Huila",
            "atl?tico huila": "Atl?tico Huila",
            "aguilas doradas": "?guilas Doradas",
            "aguilas": "?guilas Doradas",
            "aguilas doradas": "?guilas Doradas",
            "patriotas": "Patriotas Boyac?",
            "patriotas boyaca": "Patriotas Boyac?",
            "boyaca chico": "Boyac? Chic?",
            "boyac? chic?": "Boyac? Chic?",
            "envigado": "Envigado",
            "union magdalena": "Uni?n Magdalena",
            "uni?n magdalena": "Uni?n Magdalena",
            "jaguares": "Jaguares de C?rdoba",
            "jaguares cordoba": "Jaguares de C?rdoba",
            
            # ========== PER? ==========
            "universitario": "Universitario",
            "universitario de deportes": "Universitario",
            "sporting cristal": "Sporting Cristal",
            "cristal": "Sporting Cristal",
            "alianza lima": "Alianza Lima",
            "alianza": "Alianza Lima",
            "melgar": "Melgar",
            "fbc melgar": "Melgar",
            "cienciano": "Cienciano",
            "cusco": "Cusco FC",
            "cusco fc": "Cusco FC",
            "carlos stein": "Carlos Stein",
            "utc cajamarca": "UTC Cajamarca",
            "utc": "UTC Cajamarca",
            "atletico grau": "Atl?tico Grau",
            "atl?tico grau": "Atl?tico Grau",
            "carlos mannucci": "Carlos Mannucci",
            "mannucci": "Carlos Mannucci",
            "deportivo municipal": "Deportivo Municipal",
            "municipal": "Deportivo Municipal",
            "union comercio": "Uni?n Comercio",
            "uni?n comercio": "Uni?n Comercio",
            "cantolao": "Cantolao",
            "academica cantolao": "Cantolao",
            "sport boys": "Sport Boys",
            "boys": "Sport Boys",
            "ayacucho fc": "Ayacucho FC",
            "ayacucho": "Ayacucho FC",
            
            # ========== URUGUAY ==========
            "nacional": "Nacional",
            "nacional uruguay": "Nacional",
            "penarol": "Pe?arol",
            "pe?arol": "Pe?arol",
            "danubio": "Danubio",
            "defensor sporting": "Defensor Sporting",
            "defensor": "Defensor Sporting",
            "river plate uruguay": "River Plate",
            "cerro largo": "Cerro Largo",
            "cerro": "Cerro",
            "fc boston river": "Boston River",
            "boston river": "Boston River",
            "fenix": "F?nix",
            "f?nix": "F?nix",
            "wanderers": "Montevideo Wanderers",
            "montevideo wanderers": "Montevideo Wanderers",
            "racing uruguay": "Racing",
            "racing club uruguay": "Racing",
            "la luz": "La Luz",
            "plaza colonia": "Plaza Colonia",
            "deportivo maldonado": "Deportivo Maldonado",
            "maldonado": "Deportivo Maldonado",
            "progreso": "Progreso",
            
            # ========== PARAGUAY ==========
            "olimpia": "Olimpia",
            "olimpia paraguay": "Olimpia",
            "cerro porteno": "Cerro Porte?o",
            "cerro porte?o": "Cerro Porte?o",
            "libertad": "Libertad",
            "guarani paraguay": "Guaran?",
            "guaran?": "Guaran?",
            "nacional paraguay": "Nacional",
            "nacional asuncion": "Nacional",
            "sportivo ameliano": "Sportivo Ameliano",
            "ameliano": "Sportivo Ameliano",
            "tacuary": "Tacuary",
            "gral caballero jlm": "General Caballero JLM",
            "general caballero": "General Caballero JLM",
            "resistencia": "Resistencia",
            "sportivo luqueno": "Sportivo Luque?o",
            "luque?o": "Sportivo Luque?o",
            
            # ========== ECUADOR ==========
            "barcelona sc": "Barcelona SC",
            "barcelona ecuador": "Barcelona SC",
            "emelec": "Emelec",
            "liga de quito": "LDU Quito",
            "ldu quito": "LDU Quito",
            "universidad catolica ecuador": "Universidad Cat?lica",
            "independiente del valle": "Independiente del Valle",
            "independiente valle": "Independiente del Valle",
            "del valle": "Independiente del Valle",
            "aucas": "Aucas",
            "deportivo cuenca": "Deportivo Cuenca",
            "cuenca": "Deportivo Cuenca",
            "mushuc runa": "Mushuc Runa",
            "tecnico universitario": "T?cnico Universitario",
            "t?cnico universitario": "T?cnico Universitario",
            "el nacional": "El Nacional",
            "gualaceo": "Gualaceo",
            "cusco": "Cusco",
            "olmedo": "Olmedo",
            
            # ========== COSTA RICA ==========
            "saprissa": "Saprissa",
            "deportivo saprissa": "Saprissa",
            "alajuelense": "Alajuelense",
            "lda": "Alajuelense",
            "herediano": "Herediano",
            "cs herediano": "Herediano",
            "cartagines": "Cartagin?s",
            "cartagin?s": "Cartagin?s",
            "guanacasteca": "Guanacasteca",
            "ad guanacasteca": "Guanacasteca",
            "santos guapiles": "Santos de Gu?piles",
            "santos de gu?piles": "Santos de Gu?piles",
            "grecia": "Grecia",
            "ad grecia": "Grecia",
            "perez zeledon": "P?rez Zeled?n",
            "p?rez zeled?n": "P?rez Zeled?n",
            "san carlos": "San Carlos",
            "ad san carlos": "San Carlos",
            "sporting fc costa rica": "Sporting FC",
            "sporting fc": "Sporting FC",
            
            # ========== INTERNACIONAL ==========
            # Libertadores / Sudamericana
            "libertadores": "CONMEBOL Libertadores",
            "copa libertadores": "CONMEBOL Libertadores",
            "sudamericana": "CONMEBOL Sudamericana",
            "copa sudamericana": "CONMEBOL Sudamericana",
            
            # CONCACAF
            "concacaf champions": "CONCACAF Champions Cup",
            "concacaf league": "CONCACAF League",
            "concacaf central american": "CONCACAF Central American Cup",
            "concacaf caribbean": "CONCACAF Caribbean Cup",
            
            # UEFA
            "champions league": "UEFA Champions League",
            "europa league": "UEFA Europa League",
            "europa conference": "UEFA Europa Conference League",
            "conference league": "UEFA Europa Conference League",
        }
        
        # Cach? para traducciones ya realizadas
        self.cache = {}
        
    def translate(self, team_name):
        """
        Traduce un nombre de equipo al formato de la API
        """
        if not team_name:
            return team_name
            
        # Normalizar
        normalized = team_name.lower().strip()
        
        # Verificar cach?
        if normalized in self.cache:
            return self.cache[normalized]
        
        # B?squeda directa
        if normalized in self.translations:
            self.cache[normalized] = self.translations[normalized]
            return self.translations[normalized]
        
        # B?squeda por palabras (para nombres compuestos)
        palabras = normalized.split()
        for palabra in palabras:
            if len(palabra) > 2 and palabra in self.translations:
                self.cache[normalized] = self.translations[palabra]
                return self.translations[palabra]
        
        # Si no hay traducci?n, devolver original
        return team_name
    
    def add_translation(self, original, api_name):
        """A?ade una nueva traducci?n manualmente"""
        self.translations[original.lower().strip()] = api_name
    
    def get_all_api_names(self):
        """Devuelve todos los nombres de equipos de la API"""
        return sorted(list(set(self.translations.values())))

# Ejemplo de uso
if __name__ == "__main__":
    translator = TeamTranslator()
    
    print("?? PRUEBAS DEL TRADUCTOR LATINOAMERICANO:")
    print("=" * 60)
    
    test_names = [
        # M?xico
        "America", "Chivas", "Cruz Azul", "Pumas", "Tigres", "Monterrey",
        # Argentina
        "Boca", "River", "Racing", "Independiente", "San Lorenzo", "Lanus",
        # Brasil
        "Flamengo", "Corinthians", "Sao Paulo", "Palmeiras", "Gremio", "Internacional",
        # Chile
        "Colo Colo", "Universidad de Chile", "Catolica",
        # Colombia
        "Nacional", "Millonarios", "Santa Fe", "America de Cali",
        # Per?
        "Universitario", "Cristal", "Alianza",
        # Uruguay
        "Nacional", "Penarol", "Defensor",
        # Paraguay
        "Olimpia", "Cerro Porteno", "Libertad",
        # Ecuador
        "Barcelona", "Emelec", "Liga de Quito",
        # EE.UU.
        "Inter Miami", "LA Galaxy", "LAFC", "Atlanta United",
    ]
    
    for name in test_names:
        translated = translator.translate(name)
        print(f"Original: {name:25} ? API: {translated}")
